#!/bin/bash

chmod +x /usr/local/bin/setup.py

dpkg-reconfigure ca-certificates

systemctl enable ecc-setup.service
systemctl enable ecc-setup.timer

systemctl start ecc-setup.service
systemctl start ecc-setup.timer
